kind: ReplicationController
apiVersion: v1
metadata:
  name: blue-app
  labels:
    app: blue-app
spec:
  replicas: 2
  selector:
    app: blue-app
  template:
    metadata:
      labels:
        app: blue-app
    spec:
      containers:
        - name: cyan
          image: scgerkin/cyan-app:0.0.2-blue
          ports:
            - name: spring-port
              containerPort: 8080
